version: "3"
services:
  dvadmin3-web:
    container_name: dvadmin3-web
    image: changchun/dvadmin3-web-arm64:0.0.1
    ports:
      - "8883:8080"  # 宿主机8883映射到容器8080
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./media:/backend/media  # 如果需要访问媒体文件
    restart: always
